### ISSUE TITLE
401 Unauthorized after startup

### ISSUE THREAD

**Issue by benjaminlaib** [ekkash/movieo#17]
Right after starting, I get the following stacktrace:

    System.Net.WebException: The remote server returned an error: (401) Unauthorized.
       at System.Net.WebClient.DownloadFile(Uri address, String fileName)
       at Movieo.Movieo.Movieo_Load(Object sender, EventArgs e) in C:\Users\imAsh\Documents\Visual Studio 2015\Projects\Movieo - Beta 3.3\Movieo\Movieo.vb:line 94
       at System.EventHandler.Invoke(Object sender, EventArgs e)
       at System.Windows.Forms.Form.OnLoad(EventArgs e)
       at System.Windows.Forms.Form.OnCreateControl()
       at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
       at System.Windows.Forms.Control.CreateControl()
       at System.Windows.Forms.Control.WmShowWindow(Message& m)
       at System.Windows.Forms.Control.WndProc(Message& m)
       at System.Windows.Forms.Form.WmShowWindow(Message& m)
       at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

I looked into the code and found some dropbox urls at the very beginning of `Movieo.vb`, which all are unavailable in the browser as well. Could you perhaps make them available again?

Also, you might want to get rid of your username in the program's metadata so it doesn't show up anymore in stacktraces (see the `C:\Users\imAsh\Documents\Visual Studio 2015\Projects\Movieo - Beta 3.3\Movieo\Movieo.vb` path from above, which contains your username)

**Comment by ekkash** [comment]
Thanks for the bug report @benjaminlaib . I didn't flag you by the way :laughing: This project is discontinued (I need to update readme) and I recently cleared a lot its resources from my computer. However, I've still got the project so I'll see what I can do but it shouldn't be a problem. They'll most likely be uploaded to this repo as I'm preserving storage on my Dropbox. Oh, and I can't commit to github from the IDE at the moment either. Are you wanting the code? Or do you want to use the production release?
